#!/bin/bash

enable_sta_mode() {
    systemctl stop hostapd udhcpd-wlan0
    systemctl restart NetworkManager dnsmasq
}

enable_ap_mode() {
    systemctl stop NetworkManager hostapd udhcpd-wlan0
    ifconfig wlan0 192.168.42.1 up
    systemctl restart udhcpd-wlan0 dnsmasq hostapd
}

case $1 in
    "sta")
        ifconfig wlan0 down
        enable_sta_mode
        ;;
    "ap")
        ifconfig wlan0 down
        enable_ap_mode
        ;;
    *)
        echo "Usage: $0 mode[sta|ap]"
        exit 1
esac
