#!/bin/bash

# AP6212A
# BT_RST_PIN control using rfkill(bcm43xx)
# UART1

PORT=ttyS1
FIRMWARE=/etc/firmware/ap6212/4343A1.hcd
BAUDRATE=115200

rfkill block bluetooth
rfkill unblock bluetooth

brcm_patchram_plus --patchram $FIRMWARE --no2bytes --use_baudrate_for_download --baudrate $BAUDRATE --tosleep 1000 /dev/$PORT

hciattach /dev/$PORT any
hciconfig hci0 up
