# DO NOT EDIT THIS FILE
#
# Please edit Env.txt to set supported parameters
#

setenv loglevel "1"
setenv rootdev "/dev/mmcblk0p2"
setenv load_addr "0x44000000"
setenv overlay_error "false"

if itest.b *0x28 == 0x02 ; then
	echo "U-boot loaded from eMMC or secondary SD"
	setenv rootdev "/dev/mmcblk1p2"
fi

if test -e mmc 0:1 Env.txt; then
    load mmc 0:1 ${load_addr} Env.txt
    env import -t ${load_addr} ${filesize}
fi

setenv bootargs "console=${console} console=tty1 root=${rootdev} panic=10 loglevel=${loglevel}"

# Load DT file
load mmc 0:1 ${fdt_addr_r} ${fdtfile}
fdt addr ${fdt_addr_r}
fdt resize 65536

for overlay in ${overlays}; do
    if load mmc 0:1 ${load_addr} allwinner/overlay/sun50i-h5-${overlay}.dtbo; then
        echo "Applying DT overlay sun50i-h5-${overlay}.dtbo"
        fdt apply ${load_addr} || setenv overlay_error "true"
    fi
done

if test "${overlay_error}" = "true"; then
    echo "Error applying DT overlays, restoring original DT"
    load mmc 0:1 ${fdt_addr_r} ${fdtfile}
fi

load mmc 0:1 ${kernel_addr_r} uImage
booti ${kernel_addr_r} - ${fdt_addr_r}
