# DO NOT EDIT THIS FILE
#
# Please edit Env.txt to set supported parameters
#

setenv loglevel "10"
setenv rootdev "/dev/mmcblk0"
setenv initrd_addr_r "0x41080000"
setenv load_addr "0x44000000"
setenv overlay_error "false"
setenv device "0"
setenv prefix ""

if itest.b *0x10028 == 0x00 ; then
    echo "U-boot loaded from SD"
    setenv device "0"
    setenv rootdev "/dev/mmcblk0"
fi

if itest.b *0x10028 == 0x02 ; then
    echo "U-boot loaded from eMMC"
    setenv device "1"
    setenv rootdev "/dev/mmcblk2"
fi

# Configure env for mender distribution
if env exists mender_boot_part; then
    setenv device "${device}:${mender_boot_part}"
    setenv rootdev "${rootdev}p${mender_boot_part}"
    setenv prefix "boot/"
else
    setenv rootdev "${rootdev}p2"
fi

if test -e mmc ${device} ${prefix}Env.txt; then
    load mmc ${device} ${load_addr} ${prefix}Env.txt
    env import -t ${load_addr} ${filesize}
fi

setenv bootargs "console=${console} earlyprintk root=${rootdev} rw rootwait resize.root=yes panic=10 loglevel=${loglevel}"

# Load DT file
load mmc ${device} ${fdt_addr_r} ${prefix}${fdtfile}
fdt addr ${fdt_addr_r}
fdt resize 65536

for overlay in ${overlays}; do
    if load mmc ${device} ${load_addr} ${prefix}allwinner/overlay/sun50i-h5-${overlay}.dtbo; then
        echo "Applying DT overlay sun50i-h5-${overlay}.dtbo"
        fdt apply ${load_addr} || setenv overlay_error "true"
    fi
done

if test "${overlay_error}" = "true"; then
    echo "Error applying DT overlays, restoring original DT"
    load mmc ${device} ${fdt_addr_r} ${prefix}${fdtfile}
fi

load mmc ${device} ${kernel_addr_r} ${prefix}Image

if load mmc ${device} ${initrd_addr_r} ${prefix}uInitrd; then
    booti ${kernel_addr_r} ${initrd_addr_r} ${fdt_addr_r}
else
    booti ${kernel_addr_r} - ${fdt_addr_r}
fi
